[tool.poetry]
name = "comet"
version = "0.1.0"
description = "Stremio's fastest torrent/debrid search add-on."
authors = ["Goldy"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/g0ldyy/comet"

[tool.poetry.dependencies]
python = "^3.11"
rank-torrent-name = "*"
uvicorn = "*"
fastapi = "*"
aiohttp = "*"
asyncio = "*"
loguru = "*"
databases = "*"
aiosqlite = "*"
pydantic-settings = "*"
bencode-py = "*"
httpx = "*"

[tool.poetry.group.dev.dependencies]
isort = "*"
pyright = "*"
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
