services:
  comet:
    container_name: comet
    image: g0ldyy/comet:rewrite
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data/comet:/app/data
    healthcheck:
      test: wget -qO- http://127.0.0.1:8000/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
